### ISSUE TITLE
New Design: Configuration based on cost savings data

### ISSUE THREAD

**Issue by cah-sachin** [aws/iot-atlas#14]
When any Edge device sends data to cloud, it is not always necessary to send those in very frequently.  Most of the cases every 15 minutes or 20 minutes works in real time. So, if we can have design around time and size for each kind of data that will be great cost saving approach for the Edge devices.

**Comment by brettf** [comment]
Hello and thank you for the idea Sachin. 

It is clear how the batching of messages can provide cost saving benefits to any IoT solution. What is unclear is how a *cost saving design* would be a distinct pattern beyond **Issue #5 - Bulk Telemetry Data**. Specifically when Issue #5 should cover specific *batch algorithms* driven by time and size and overall [data density](https://iotatlas.net/glossary/vocabulary/#device-data-density).

What other ways have you seen IoT solutions, old and new, save costs beyond the tactic of sending telemetry data in bulk? Most tactics beyond that "bulk send" seem to need to take into account vendor-specific costs and therefore seem to be more specific to a provider than a general IoT design pattern. 

But it would be beneficial to hear more ideas if you can share them. Maybe those ideas are additional *considerations* for Issue #5, or maybe they represent an entirely new *cost saving* pattern. 

We look forward to your thoughts.

**Comment by brettf** [comment]
@cah-sachin it would be great to get more of your thoughts on this. 
For now I will close this Issue but can reopen for future consideration - once more context is added.
