### ISSUE TITLE
Explore IoT atlas

### ISSUE THREAD

**Issue by achandana** [aws/iot-atlas#24]
Hi Guys,

I just wanted to explore IoT Atlas what are all software need to install and how to start this. Could any one please help me.

**Comment by brettf** [comment]
Right now we use `hugo` to stand up everything. The simplest way to see what's up for running a copy of the IoT Atlas is to [learn about Hugo](https://gohugo.io/getting-started/quick-start/) and then review the [config.json](https://github.com/aws/iot-atlas/blob/master/config.json) file. With those two artifacts we hope someone can stand-up an IoT Atlas copy for your own use.

**Comment by gadams999** [comment]
Hi @achandana!

With the recent theme changes, we have also introduced using containers to perform local development and testing of content. Please refer the [development README](https://github.com/aws/iot-atlas/blob/main/src/README.md) and the [Contributor to the Atlas](https://iotatlas.net/en/contribute/) sections for more details.
