### ISSUE TITLE
Height of the language selection dropdown box is too small

### ISSUE THREAD

**Issue by michaelgarcia** [aws/iot-atlas#25]
The height of the language selection dropdown box is too small.

It is still possible to see that it is a selection bar with a language but the text is cropped by the height being too small.

It is not a major problem as the location of that dropdown list and the crop text is enough to understand that it is probably the language selection dropdown. Once you click on the box the languages appear clearly.

**Comment by gadams999** [comment]
Hi Michael, closing this out due to the change from dockdoc to the Hugo Learn Theme. Please open a new issue if there is still formatting changes required.
